resources:
- service-account.yaml
- role.yaml
- role-binding.yaml
- job.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: karlkfi/kubexit
  newName: karlkfi/kubexit
  newTag: latest
- name: karlkfi/test-client
  newName: karlkfi/test-client
  newTag: latest
